Get artifacts on any build result (#4)

diff --git a/scripts/start-build b/scripts/start-build
--- a/scripts/start-build
+++ b/scripts/start-build
@@ -224,21 +224,6 @@ if [ ${WAIT_FOR_CODEBUILD} = "true" ]; then
     quiet=$(s3_put_result)
   fi
 
-  # Extract build status from job details
-  codebuild_status=`echo ${build_result} | jq -c -r '.buildStatus'`;
-
-  # Build succeeded
-  echo
-  if [ ${codebuild_status} = "SUCCEEDED" ]; then
-    echo "-> Build ${start_build_id} completed successfully!"
-
-  # Build failed
-  else
-    echo "-> Build ${start_build_id} failed!"
-    echo "Build failure reason: ${codebuild_status}"
-    exit 1;
-  fi
-
   # Artifacts
   artifacts=`echo ${build_result} | jq -c -r '.artifacts'`;
   artifacts_location=`echo ${artifacts} | jq -c -r '.location'`;
@@ -275,6 +260,21 @@ if [ ${WAIT_FOR_CODEBUILD} = "true" ]; then
       echo "Unsupported CODEBUILD_ARTIFACTS_PACKAGING value"
     fi
 
+  fi
+
+  # Extract build status from job details
+  codebuild_status=`echo ${build_result} | jq -c -r '.buildStatus'`;
+
+  # Build succeeded
+  echo
+  if [ ${codebuild_status} = "SUCCEEDED" ]; then
+    echo "-> Build ${start_build_id} completed successfully!"
+
+  # Build failed
+  else
+    echo "-> Build ${start_build_id} failed!"
+    echo "Build failure reason: ${codebuild_status}"
+    exit 1;
   fi
 
 fi
